### ISSUE TITLE
How to install linux driver for dummies

### ISSUE THREAD

**Issue by muzzaau008** [SeeedDocument/USB-CAN-Analyzer#1]
Hi,
can you detail how to install the linux driver for dummies like me. I'm new to linux. I recently got a usb-can-analyzer and can't get it to work.

**Comment by eddylai** [comment]
no need to install any driver,
just check if there's a /dev/ttyUSB0 (or 1,2.3....) device node after you plug  in the USB cable.

**Comment by muzzaau008** [comment]
Yes, I did see that, but it still didn't work. Maybe its something else. I will have to look into it some more.
